### ISSUE TITLE
Radio buttons styles

### ISSUE THREAD

**Issue by matthewford** [ministryofjustice/govuk_elements_form_builder#17]
Either the default or inline
https://github.com/alphagov/govuk_elements/blob/master/views/snippets/form_radio_buttons.html
https://github.com/alphagov/govuk_elements/blob/master/views/snippets/form_radio_buttons_inline.html

**Comment by aliuk2012** [comment]
Hey @matthewford, I'm working on getting the radio buttons which will hopefully be out shortly. Some of the GDS does seem weird to create as as part of a form builder. example in the examples you provided they use h1 before the radio buttons which is not ideal if you have other headings and fields on the page and so using h1 would not be semantically correct.

**Comment by matthewford** [comment]
Yeah, actually we ended up using our own markup/styles for the queens awards which just visually looks similar

**Comment by matthewford** [comment]
Although is the h1 actually part of the button, I thought that was just a example page heading.
