### ISSUE TITLE
Add error validation examples to visual guide

### ISSUE THREAD

**Issue by robmckinnon** [ministryofjustice/govuk_elements_form_builder#30]
Add examples of error validation generation, equivalent to the error documentation for GOV.UK elements here: https://govuk-elements.herokuapp.com/errors/#summarise-errors

**Comment by robmckinnon** [comment]
You can see guide changes here: https://govuk-elements-rails-guide.herokuapp.com

Pull request here: https://github.com/ministryofjustice/govuk_elements_rails_guide/pull/3

**Comment by aliuk2012** [comment]
PR has been merged
