### ISSUE TITLE
Ruby version too restrictive

### ISSUE THREAD

**Issue by stephenrichards** [ministryofjustice/govuk_elements_form_builder#70]
The gemspec specifies ruby 2.3.1 and there is code which uses the new &. instead of .try.

This means apps which use this gem cannot be deployed to Heroku which only supports 2.2.5

**Comment by aliuk2012** [comment]
Hi @stephenrichards, Heroku does support 2.3.1 but by default it uses is 2.2.5. To get 2.3.1 you have to specify the ruby version in your Gemfile.

https://github.com/ministryofjustice/govuk_elements_rails_guide/blob/master/Gemfile#L21-L23
https://devcenter.heroku.com/articles/ruby-support
https://devcenter.heroku.com/articles/ruby-versions
